FROM python:3.9-slim
RUN apt-get update && apt-get install -y openssh-client sshpass && apt-get clean && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY possible_passwords.txt .
COPY brute_force_ssh.py .
CMD ["python", "brute_force_ssh.py"]